<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name . ' - ' . Lang::t('general', 'Privacy Policy');
?>
<div class="policy-page">
    <h1><?php echo Lang::t('general', 'Privacy Policy'); ?></h1>
<p>Ch&uacute;ng t&ocirc;i &ndash; c&ocirc;ng ty Cổ phần dịch vụ trực tuyến Dream Weavers Media (bao gồm cả những chi nh&aacute;nh, gọi chung l&agrave; &ldquo;DWM&rdquo; ) cam kết bảo vệ quyền ri&ecirc;ng tư của những người sử dụng dịch vụ. Ch&uacute;ng t&ocirc;i đ&atilde; sọan thảo ch&iacute;nh s&aacute;ch bảo mật n&agrave;y để th&ocirc;ng b&aacute;o cho bạn c&aacute;ch ch&uacute;ng t&ocirc;i xử l&yacute; những th&ocirc;ng tin m&agrave; ch&uacute;ng t&ocirc;i thu thập được hoặc do bạn gửi đến. Trừ phi c&oacute; những ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tự đặc biệt tại những trang đặc biệt, ch&iacute;nh s&aacute;ch bảo mật n&agrave;y &aacute;p dụng cho tất cả c&aacute;c trang mạng của DWM bao gồm KelReport (www.kelreport.com) v&agrave; PLUN.ASIA (www.plun.asia), gọi chung l&agrave; &ldquo;Mạng lưới&rdquo;, hoặc bất cứ phi&ecirc;n bản n&agrave;o của ch&uacute;ng. V&igrave; Mạng Lưới mang t&iacute;nh to&agrave;n cầu, những th&ocirc;ng tin về bạn m&agrave; ch&uacute;ng t&ocirc;i g&oacute;p nhặt được hoặc do bạn gửi đến c&oacute; thể được chuyển đổi, xử l&yacute; v&agrave; lưu trữ ở những quốc gia kh&aacute;c. Với việc sử dụng Mạng Lưới, bạn đ&atilde; nghiễm nhi&ecirc;n đồng &yacute; về c&aacute;ch sử dụng th&ocirc;ng tin như tr&ecirc;n. Ch&iacute;nh s&aacute;ch bảo mật n&agrave;y cũng h&ograve;an t&ograve;an ph&ugrave; hợp với Nguy&ecirc;n tắc che giấu an to&agrave;n của Ủy Ban Ch&acirc;u &Acirc;u về bảo mật dữ liệu</p>

<p><strong>Th&ocirc;ng tin thu thập tự động</strong></p>

<p>Ch&uacute;ng t&ocirc;i sẽ thu thập tự động một số th&ocirc;ng tin để hiểu hơn về c&aacute;ch thức người d&ugrave;ng sử dụng Mạng Lưới (trong ch&iacute;nh s&aacute;ch bảo mật n&agrave;y ch&uacute;ng t&ocirc;i sẽ gọi chung l&agrave; dữ liệu về c&aacute;ch d&ugrave;ng). V&iacute; dụ như mỗi lần bạn truy cập Mạng Lưới, ch&uacute;ng t&ocirc;i sẽ tự động ghi nhận địa chỉ IP của bạn, tr&igrave;nh duyệt web v&agrave; lọai m&aacute;y t&iacute;nh truy cập, số lần truy cập, trang web đ&atilde; xem trước đ&oacute; v&agrave; những trang web bạn đ&atilde; truy cập. Th&ecirc;m v&agrave;o đ&oacute;, ch&uacute;ng t&ocirc;i sử dụng những kỹ thuật gọi l&agrave; &ldquo;cookies&rdquo; v&agrave; &ldquo;Tracking pixels&rdquo; cho ph&eacute;p ch&uacute;ng t&ocirc;i hỗ trợ bạn trong việc sử dụng mạng lưới (v&iacute; dụ như ghi nhận lại những thứ bạn đ&atilde; mua, cho ph&eacute;p bạn xem lại những th&ocirc;ng tin đ&atilde; xem trước đ&oacute; (như những lựa chọn trong c&aacute;c cuộc thăm d&ograve; th&agrave;nh vi&ecirc;n), thể hiện những nội dung đặc biệt ph&ugrave; hợp với sở th&iacute;ch, v&agrave; nếu bạn cho ph&eacute;p ch&uacute;ng t&ocirc;i sẽ lưu lại t&ecirc;n truy cập v&agrave; mật m&atilde; để bạn kh&ocirc;ng phải g&otilde; lại mỗi khi bạn truy cập v&agrave;o Mạng Lưới hoặc những khu vực trong Mạng Lưới m&agrave; đ&ograve;i hỏi phải đăng nhập). Ch&uacute;ng t&ocirc;i sử dụng cookies để gửi đến bạn những mẩu quảng c&aacute;o ph&ugrave; hợp với sở th&iacute;ch của bạn nhất, dựa tr&ecirc;n những khu vực m&agrave; bạn hay truy cập tr&ecirc;n to&agrave;n Mạng Lưới v&agrave; những sản phẩm dịch vụ bạn chọn tr&ecirc;n Mạng Lưới. Ch&uacute;ng t&ocirc;i cũng c&oacute; thể sẽ d&ugrave;ng cookies hoặc Tracking pixels để theo dấu c&aacute;c th&ocirc;ng tin li&ecirc;n quan đến những th&agrave;nh vi&ecirc;n kh&aacute;c m&agrave; bạn truy cập hoặc t&igrave;m kiếm chẳng hạn như những hồ sơ người d&ugrave;ng m&agrave; bạn truy cập hoặc gửi phản hồi, t&igrave;m kiếm c&aacute;c th&ocirc;ng số của c&ocirc;ng cụ t&igrave;m kiếm m&agrave; bạn sử dụng, số lượng kết quả trả về bởi c&ocirc;ng cụ t&igrave;m kiếm, c&aacute;ch bạn nh&igrave;n nhận, đ&aacute;nh gi&aacute; v&agrave; phản hồi về kết quả t&igrave;m kiếm, v&agrave; thường th&igrave; bao l&acirc;u th&igrave; hồ sơ của được truy cập v&agrave; t&igrave;m kiếm một lần. Ch&uacute;ng tội c&oacute; thể d&ugrave;ng những th&ocirc;ng tin n&agrave;y để ph&aacute;t triển những t&iacute;nh năng của Mạng Lưới v&agrave; để đưa ra những dịch vụ phụ trội chẳng hạn như tăng cường khả năng t&igrave;m kiếm hoặc khả năng tự động t&igrave;m kết quả ph&ugrave; hợp với người d&ugrave;ng.</p>

<p>Hơn nữa, những đệ tam nh&acirc;n đặt quảng c&aacute;o tr&ecirc;n mạng lưới cũng c&oacute; thể thu thập th&ocirc;ng tin th&ocirc;ng qua cookies v&agrave; Tracking pixels để đảm bảo rằng những hệ thống v&agrave; kỹ thuật quảng c&aacute;o của họ c&oacute; hiệu quả v&agrave; cho ph&eacute;p họ theo d&otilde;i những th&ocirc;ng tin phản hồi về những phần quảng c&aacute;o của họ. C&aacute;c Cookies hoặc Tracking pixels thiết lập bởi c&aacute;c b&ecirc;n thứ ba n&oacute;i tr&ecirc;n được quản l&yacute; bới ch&iacute;nh s&aacute;ch bảo mật do ch&iacute;nh họ tạo n&ecirc;n. Th&ecirc;m v&agrave;o đ&oacute;, những dơn vị c&oacute; li&ecirc;n quan đến b&ecirc;n thứ ba, những nh&agrave; quảng c&aacute;o v&agrave; những trang mạng kh&aacute;c m&agrave; bạn truy cập v&agrave;o từ Mạng Lưới c&oacute; những ch&iacute;nh s&aacute;ch bảo mật kh&aacute;c biệt nhau v&agrave; kh&ocirc;ng li&ecirc;n quan g&igrave; đến ch&iacute;nh s&aacute;ch bảo mật n&agrave;y. Ch&uacute;ng t&ocirc;i khuy&ecirc;n bạn n&ecirc;n đọc những điều lệ trong ch&iacute;nh s&aacute;ch bảo mật của từng trang mạng để t&igrave;m hiểu c&aacute;ch m&agrave; những th&ocirc;ng tin của bạn được bảo vệ. Nếu bạn m&uacute;&ocirc;n t&igrave;m hiểu th&ecirc;m th&ocirc;ng tin về những quy tr&igrave;nh tr&ecirc;n v&agrave; kh&ocirc;ng muốn th&ocirc;ng tin của m&igrave;nh bị sử dụng bởi c&aacute;c c&ocirc;ng ty/ đơn vị n&oacute;i tr&ecirc;n, xin vui l&ograve;ng bấm v&agrave;o <a href="http://networkadvertising.org/consumer/opt_out.asp">đ&acirc;y</a>.</p>

<p>Sau n&agrave;y ch&uacute;ng t&ocirc;i c&oacute; thể sẽ chia sẻ Dữ liệu người d&ugrave;ng với đơn vị thứ ba. Tuy nhi&ecirc;n ch&uacute;ng t&ocirc;i chỉ thực hiện quy tr&igrave;nh n&oacute;i tr&ecirc;n khi c&oacute; sự nhất tr&iacute; v&agrave; kh&ocirc;ng để xảy ra t&igrave;nh trạng b&ecirc;n thứ ba tiếp nhận những th&ocirc;ng tin mang t&iacute;nh c&aacute; nh&acirc;n trừ khi được bạn cho ph&eacute;p. Th&ecirc;m v&agrave;o đ&oacute;, ch&uacute;ng t&ocirc;i c&oacute; thể kết hợp Dữ liệu người d&ugrave;ng với Th&ocirc;ng tin c&aacute; nh&acirc;n (sẽ định nghĩa b&ecirc;n dưới) để c&oacute; thể truy xuất th&ocirc;ng tin dữ liệu người d&ugrave;ng đến từng c&aacute; nh&acirc;n sử dụng. Tuy nhi&ecirc;n ch&uacute;ng t&ocirc;i chỉ l&agrave;m thế cho những mục đ&iacute;ch của ri&ecirc;ng ch&uacute;ng t&ocirc;i v&agrave; sẽ kh&ocirc;ng chia sẻ lọai th&ocirc;ng tin kết hợp n&agrave;y với b&ecirc;n thứ ba trừ phi bạn cho ph&eacute;p hoặc ch&uacute;ng t&ocirc;i phải l&agrave;m điều đ&oacute; theo y&ecirc;u cầu cảu luật ph&aacute;p.</p>

<p><strong>Th&ocirc;ng tin bạn chọn đăng</strong></p>

<p>Khi bạn đăng k&yacute; trở th&agrave;nh một th&agrave;nh vi&ecirc;n của Mạng Lưới hoặc khi bạn tham gia những họat động n&agrave;o đ&oacute; của Mạng Lưới (V&iacute; dụ: Tham gia dự thi hoặc l&agrave;m khảo s&aacute;t ), ch&uacute;ng t&ocirc;i c&oacute; thể y&ecirc;u cầu bạn cung cấp những th&ocirc;ng tin cơ bản ( V&iacute; dụ: Giới t&iacute;nh, tuổi, m&atilde; quốc gia) v&agrave; những th&ocirc;ng tin để li&ecirc;n lạc (V&iacute; dụ: t&ecirc;n họ đầy đủ, địa chỉ hộp thư hoặc địa chỉ mail hay số điện thọai) (Những th&ocirc;ng tin n&agrave;y ch&uacute;ng t&ocirc;i gọi l&agrave; Th&ocirc;ng tin c&aacute; nh&acirc;n trong ch&iacute;nh s&aacute;ch bảo mật n&agrave;y). Ngọai trừ những th&ocirc;ng tin cơ bản được ph&eacute;p c&ocirc;ng bố, ch&uacute;ng t&ocirc;i chỉ chia sẻ dữ liệu với b&ecirc;n thứ ba theo c&aacute;ch kh&ocirc;ng gắn những dự liệu n&agrave;y trực tiếp với từng người d&ugrave;ng, ch&uacute;ng t&ocirc;i cũng kh&ocirc;ng chia sẻ Th&ocirc;ng tin c&aacute; nh&acirc;n của bạn với b&ecirc;n thứ ba trừ phi bạn cho ph&eacute;p . Th&ecirc;m v&agrave;o đ&oacute;, khi bạn y&ecirc;u cầu một sản phẩm hoặc dịch vụ n&agrave;o đ&oacute; th&ocirc;ng qua Mạng Lưới, ch&uacute;ng t&ocirc;i sẽ y&ecirc;u cầu bạn cung cấp những th&ocirc;ng tin để c&oacute; thể đ&aacute;p ứng nhu cầu của bạn như số thẻ t&iacute;n dụng, h&oacute;a đơn v&agrave; th&ocirc;ng tin k&yacute; gửi. Ch&uacute;ng t&ocirc;i sẽ chia sẻ những th&ocirc;ng tin (v&iacute; dụ , với người b&aacute;n h&agrave;ng) với b&ecirc;n thứ ba để đ&aacute;p ứng đầy đủ nhu cầu của bạn hoặc để h&ograve;an chỉnh họat động của Mạng Lưới.</p>

<p><strong>C&ocirc;ng bố th&ocirc;ng tin hợp ph&aacute;p</strong></p>

<p>Ch&uacute;ng t&ocirc;i c&oacute; thể chia sẻ những th&ocirc;ng tin đ&atilde; thu thập được hoặc do bạn gửi về m&agrave; kh&ocirc;ng hề tr&aacute;i lại với ch&iacute;nh s&aacute;ch bảo mật n&oacute;i tr&ecirc;n trong những trường hợp như sau :</p>

<p>(1) Phản hồi th&ocirc;ng tin cho c&aacute;c giấy b&aacute;o, theo y&ecirc;u cầu của t&ograve;a &aacute;n, những quy tr&igrave;nh ph&aacute;p l&yacute;, hoặc để thiết lập, bảo vệ, thực thi quyền ph&aacute;p l&yacute; hoặc để chống lại những c&aacute;o buộc ph&aacute;p l&yacute;;</p>

<p>(2) Khi cần thiết để phục vụ điều tra, ngăn chặn hoặc xem x&eacute;t những họat động bất hợp ph&aacute;p hoặc những t&igrave;nh huống c&oacute; mang hiểm họa tiềm t&agrave;ng đến sự an t&ograve;an của bất cứ c&aacute; nh&acirc;n n&agrave;o</p>

<p>(3) Khi cần thiết để phục vụ điều tra, ngăn chặn hoặc xem x&eacute;t những t&igrave;nh huống c&oacute; li&ecirc;n quan đến lạm dụng hạ tầng kỹ thuật mạng lưới hoặc mạng Internet n&oacute;i chung (chẳng hạn như spam li&ecirc;n tục, từ chối tấn c&ocirc;ng dịch vụ, hoặc những nỗ lực để đảm bảo bảo mật hạ tầng kỹ thuật mạng lưới);</p>

<p>(4) Cho c&ocirc;ng ty mẹ, những chi nh&aacute;nh, c&ocirc;ng ty cổ phần hoặc những c&ocirc;ng ty kh&aacute;c dưới sự điều h&agrave;nh chung của DWM (trong trừơng hợp n&agrave;y ch&uacute;ng t&ocirc;i sẽ đề nghị những đơn vị sử dụng th&ocirc;ng tin đảm bảo những điều khỏan đ&atilde; n&ecirc;u trong ch&iacute;nh s&aacute;ch bảo mật n&agrave;y);</p>

<p>(5) Nếu DWM được y&ecirc;u cầu s&aacute;t nhập với một c&ocirc;ng ty kh&aacute;c (trong trường hợp n&agrave;y ch&uacute;ng t&ocirc;i sẽ y&ecirc;u cầu c&ocirc;ng ty đối t&aacute;c đảm bảo những điều đ&atilde; cam kết trong ch&iacute;nh s&aacute;ch bảo mật n&agrave;y).</p>

<p><strong>Những khu vực c&ocirc;ng cộng</strong></p>

<p>Việc bạn sử dụng những khu vực tr&ecirc;n Mạng lưới để giao tiếp với những người d&ugrave;ng kh&aacute;c (chẳng hạn như quảng c&aacute;o ri&ecirc;ng, những ph&ograve;ng chat, hiển thị online hay bảng tin nhắn) c&oacute; thể để lại t&ecirc;n th&agrave;nh vi&ecirc;n v&agrave; địa chỉ email v&agrave; c&oacute; thể để lộ ra một lượng th&ocirc;ng tin c&aacute; nh&acirc;n nhất định.Khi sử dụng những khu vực n&agrave;y tức l&agrave; bạn đ&atilde; hiểu v&agrave; đồng &yacute; rằng bất cứ một ai cũng c&oacute; thể tiếp cận v&agrave; chuyển tiếp những th&ocirc;ng tin về bạn được chứa đựng trong những b&agrave;i bạn đ&atilde; đăng trong c&aacute;c khu vực. Trong khi tr&ograve; chuyện chat, gửi email hay tin nhắn &ndash; những h&igrave;nh thức tr&ograve; chuyện th&ocirc;ng qua những m&aacute;y chủ của ch&uacute;ng t&ocirc;i, hệ thống ch&uacute;ng t&ocirc;i họat động sẽ kh&ocirc;ng lưu trữ nội dung của c&aacute;c cuộc tr&ograve; chuyện n&agrave;y. Tuy nhi&ecirc;n ch&uacute;ng t&ocirc;i sẽ tạm thời lưu trữ một số dự liệu nhất định li&ecirc;n quan đến nội dung của cuộc giao tiếp chẳng hạn như độ d&agrave;i v&agrave; tần số của những tin nhắn v&agrave; th&agrave;nh vi&ecirc;n mạng lưới đ&atilde; tham gia cuộc hội thọai. Ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng dữ liệu để tăng cường chức năng của Mạng Lưới v&agrave; đưa ra những dịch vụ phụ trội chẳng hạn như tăng cường khả năng t&igrave;m kiếm hoặc khả năng tự động t&igrave;m kết quả ph&ugrave; hợp với người d&ugrave;ng .</p>

<p><strong>Bảo mật v&agrave; bảo to&agrave;n dữ liệu</strong></p>

<p>Ch&uacute;ng t&ocirc;i c&oacute; một số biện ph&aacute;p ph&ograve;ng ngừa để bảo vệ th&ocirc;ng tin c&aacute; nh&acirc;n của người d&ugrave;ng khỏi bị mất m&aacute;t, sử dụng sai mục đ&iacute;ch v&agrave; tiếp cận tr&aacute;i ph&eacute;p, tuy&ecirc;n truyền, sửa đổi v&agrave; ti&ecirc;u hủy. Ch&uacute;ng t&ocirc;i cũng c&oacute; một số bước để đảm bảo những th&ocirc;ng tin c&aacute; nh&acirc;n của người d&ugrave;ng được sử dụng đ&uacute;ng mục đ&iacute;ch v&agrave; những dữ liệu người d&ugrave;ng n&agrave;y đ&aacute;ng tin cậy để sử dụng sao cho ch&iacute;nh x&aacute;c, h&ograve;an chỉnh v&agrave; kịp thời.</p>

<p>Nếu bạn muốn điều chỉnh bất kỳ th&ocirc;ng tin c&aacute; nh&acirc;n n&agrave;o m&agrave; bạn đ&atilde; đăng k&yacute; trước đ&acirc;y cho Mạng lưới, h&atilde;y truy cập v&agrave;o khu vực th&ocirc;ng tin t&agrave;i khỏan của bạn tại mỗi trang mạng m&agrave; bạn đ&atilde; đăng k&yacute; tr&ecirc;n Mạng Lưới. Nếu bạn đồng &yacute; nhận th&ocirc;ng tin từ ch&uacute;ng t&ocirc;i hoặc cho ph&eacute;p ch&uacute;ng t&ocirc;i chia sẻ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn với b&ecirc;n thứ ba, về sau n&agrave;y bạn c&oacute; thể y&ecirc;u cầu ch&uacute;ng t&ocirc;i kh&ocirc;ng gửi những th&ocirc;ng tin n&agrave;y hoặc chia sẻ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn nữa bằng c&aacute;ch viết thư cho trung t&acirc;m chăm s&oacute;c kh&aacute;ch h&agrave;ng/ th&agrave;nh vi&ecirc;n tại địa chỉ b&ecirc;n dưới hoặc truy cập v&agrave;o khu vực th&ocirc;ng tin t&agrave;i khỏan của bạn tại mỗi trang mạng tr&ecirc;n Mạng lưới. Tuy nhi&ecirc;n, xin h&atilde;y lưu &yacute; rằng ch&uacute;ng t&ocirc;i giữ quyền gửi cho bạn những tin nhắn điều h&agrave;nh c&oacute; li&ecirc;n quan đến Mạng Lưới chẳng hạn như những thay đổi đối với ch&iacute;nh s&aacute;ch bảo mật n&agrave;y. Tại bất cứ thời điểm n&agrave;o, nếu bạn muốn tắt hồ sơ người d&ugrave;ng của m&igrave;nh v&agrave; x&oacute;a hồ sơ khỏi sự truy cập của những người d&ugrave;ng kh&aacute;c tr&ecirc;n t&ograve;an Mạng Lưới, xin viết thư cho ch&uacute;ng t&ocirc;i v&agrave; gửi về địa chỉ b&ecirc;n dưới hoặc truy cập v&agrave;o khu vực th&ocirc;ng tin t&agrave;i khoản của bạn tại mỗi trang mạng tr&ecirc;n Mạng lưới. Xin lưu &yacute; rằng (1) ch&uacute;ng t&ocirc;i sẽ lưu giữ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn tại bộ phận lưu trữ sau khi tắt v&agrave; (2) ch&uacute;ng t&ocirc;i sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm về việc x&oacute;a bỏ th&ocirc;ng tin của bạn tr&ecirc;n hệ thống dữ liệu của bất kỳ b&ecirc;n thứ ba n&agrave;o m&agrave; bạn đ&atilde; cho ph&eacute;p ch&uacute;ng t&ocirc;i chia sẻ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn trước đ&acirc;y.</p>

<p>Để c&oacute; th&ecirc;m những m&ocirc; tả đầy đủ hơn về ch&iacute;nh s&aacute;ch bảo mật n&agrave;y, bạn c&oacute; thể y&ecirc;u cầu DWM kh&ocirc;ng c&ocirc;ng bố th&ocirc;ng tin c&aacute; nh&acirc;n của bạn với b&ecirc;n thứ ba. Bạn cũng c&oacute; thể l&agrave;m việc n&agrave;y v&agrave;o l&uacute;c bạn đăng k&yacute; hoặc li&ecirc;n lạc với ch&uacute;ng t&ocirc;i qua thư tại:<br />
<br />
Dream Weavers Media<br />
Ph&ograve;ng Dịch vụ v&agrave; chăm s&oacute;c kh&aacute;ch h&agrave;ng (CMS)<br />
Tầng trệt, l&ocirc; C, cao ốc Ph&uacute;c Thịnh<br />
341 Cao Đạt, Quận 5 Tp.HCM, VietNam<br />
Email: <a href="mailto:cms@kelreport.com">cms@kelreport.com</a></p>

<p><strong>Những thay đổi ch&iacute;nh s&aacute;ch</strong></p>

<p>V&igrave; những thay đổi về mặt luật ph&aacute;p, kinh nghiệm đuc kết hoặc sự thay đổi về chức năng v&agrave; nội dung, ch&uacute;ng t&ocirc;i c&oacute; thể sẽ thay đổi ch&iacute;nh s&aacute;ch bảo mật v&agrave; sẽ phản &aacute;nh những sự thay đổi trong văn bản n&agrave;y. Ch&uacute;ng t&ocirc;i sẽ cập nhật ch&iacute;nh s&aacute;ch n&agrave;y thường xuy&ecirc;n. Nếu c&oacute; những sự thay đổi đ&aacute;ng kể về c&aacute;ch thức xử l&yacute; th&ocirc;ng tin c&aacute; nh&acirc;n của bạn, ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o cho bạn những sự thay đổi n&agrave;y qua email hoặc đăng b&agrave;i lưu &yacute; tr&ecirc;n những trang mạng / khu vực c&oacute; li&ecirc;n quan tr&ecirc;n mạng lưới. Nếu bạn c&oacute; thắc mắc g&igrave; về ch&iacute;nh s&aacute;ch bảo mật n&agrave;y, xin vui l&ograve;ng gửi thư cho ch&uacute;ng t&ocirc;i tại địa chỉ tr&ecirc;n</p>
    

</div>
<div class="clear"></div>